name: Main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: ./node_modules/.bin/nps test.unit
      - run: ./node_modules/.bin/nps lint
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build:
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: arnaudboeglin/javachess-client
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "release-${{ github.run_number }},latest"
          buildargs: SOCKET_ENDPOINT=http://www.easychess.xyz/api/ws, CHESS_SERVICE_ENDPOINT=http://www.easychess.xyz/api

  deploy:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - name: Save DigitalOcean kubeconfig
        env:
          CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        run: doctl kubernetes cluster kubeconfig save $CLUSTER_NAME
      - name: Update container image
        run: kubectl -n apps set image deployment/client "client=arnaudboeglin/javachess-client:release-${{ github.run_number }}" --record
